package com.liping.utils;

public interface ErrorConstans
{
	Integer FORBIDEN = 403;
	String QUERY_USER_ERROR = "LP_0000";
	String NULL_PARAMETER_ERROR = "LP_0001";
	String INSERT_USER_ERROR = "LP_0002";
	String DELETE_USER_ERROR = "LP_0003";
	String INVALID_PARAMETER_ERROR = "LP_0004";
	String GET_TOKEN_ERROR = "LP_0005";
	String DECODE_MESSAGE_ERROR = "LP_0006";
	String REGISTER_IAM_USER_ERROR = "LP_0007";
	String UPDATE_IAM_USER_ERROR = "LP_0007";
}
